mod 'puppetlabs/ntp', '4.2.0'
mod 'puppetlabs/puppetdb', '5.1.2'
mod 'puppetlabs/stdlib', '4.12.0'
mod 'puppetlabs/concat', '2.2.0'
mod 'puppetlabs/inifile', '1.5.0'
mod 'puppetlabs/postgresql', '4.7.1'
mod 'puppetlabs/firewall', '1.8.1'
